services:
  database:
    image: alpine/sqlite:latest
    volumes:
      - db_data:/data
    command: tail -f /dev/null 
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/app
      - db_data:/db_volume
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge