"""add quotient_caf and nb_enfants cols to clients

Revision ID: 738329a36975
Revises: fe4c68c62c61
Create Date: 2025-06-24 12:06:47.588389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738329a36975'
down_revision: Union[str, Sequence[str], None] = 'fe4c68c62c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('nb_enfants', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('quotient_caf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'quotient_caf')
    op.drop_column('clients', 'nb_enfants')
    # ### end Alembic commands ###
