"""add new columns in clients

Revision ID: a873cfb5de25
Revises: 303df932657e
Create Date: 2025-06-22 21:40:04.417070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a873cfb5de25'
down_revision: Union[str, Sequence[str], None] = '303df932657e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('nb_enfants', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('quotient_caf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'quotient_caf')
    op.drop_column('clients', 'nb_enfants')
    # ### end Alembic commands ###
