"""add nb_enfants and quotient_caf columns to clients

Revision ID: b5b95330e0a3
Revises: 3ac8a6f558d9
Create Date: 2025-06-23 22:58:36.167490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b95330e0a3'
down_revision: Union[str, Sequence[str], None] = '3ac8a6f558d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('nb_enfants', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('quotient_caf', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'quotient_caf')
    op.drop_column('clients', 'nb_enfants')
    # ### end Alembic commands ###
