"""first clients migration

Revision ID: da72b84b8182
Revises: b5b95330e0a3
Create Date: 2025-06-24 09:53:20.460540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da72b84b8182'
down_revision: Union[str, Sequence[str], None] = 'b5b95330e0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'quotient_caf')
    op.drop_column('clients', 'nb_enfants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('nb_enfants', sa.INTEGER(), nullable=True))
    op.add_column('clients', sa.Column('quotient_caf', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
